### ISSUE TITLE
Improve Mobile/Responsive Experience of the App

### ISSUE THREAD

**Issue by MarcoMorawec** [masterbrent/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by masterbrent** [comment]
I've added   <meta name="viewport" content="width=device-width"> to application.html.erb

**Comment by MarcoMorawec** [comment]
:+1: @masterbrent 

Make sure you close this issue now that you have everything fixed :)
